### ISSUE TITLE
Overlap of footer on page content

### ISSUE THREAD

**Issue by alavatelliMCA** [coyote-team/coyote#393]
This is related to #343 but separating into a new ticket. because the overlap issue is occurring in other contexts. "I need a hint" is half covered on the clue page when you scroll all the way up.

![img_0635](https://user-images.githubusercontent.com/8040710/46567614-4da7f700-c8fb-11e8-8b7f-7a416b253c0d.PNG)

(sorry I put a kibosh on new tickets, but this is critical for use and related to already open tickets)

**Comment by stacietaylorcima** [comment]
@alavatelliMCA Can you check that this one is fixed now and close if it is?

**Comment by alavatelliMCA** [comment]
Sorry screenshot was from live, but issue is also on staging, so sorry... still an issue.

![img_0636](https://user-images.githubusercontent.com/8040710/46567644-b7280580-c8fb-11e8-974f-3a18b4bc997b.PNG)

**Comment by alavatelliMCA** [comment]
I'm on staging, and this is looking good!

**Comment by stacietaylorcima** [comment]
@alavatelliMCA What are you seeing now?
